version: '3'

services:
  php:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: blog
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
